export const tvTypes = {
  START_LOADING_POPULAR_TV: "START_LOADING_POPULAR_TV",
  ERROR_LOADING_POPULAR_TV: "ERROR_LOADING_POPULAR_TV",
  SUCCESS_LOADING_POPULAR_TV: "SUCCESS_LOADING_POPULAR_TV",
};
