export const movieTypes = {
  START_LOADING_POPULAR_MOVIES: "START_LOADING_POPULAR_MOVIES",
  ERROR_LOADING_POPULAR_MOVIES: "ERROR_LOADING_POPULAR_MOVIES",
  SUCCESS_LOADING_POPULAR_MOVIES: "SUCCESS_LOADING_POPULAR_MOVIES",
};
